apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myweb
  namespace: ingress-myweb
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
spec:
  ingressClassName: myweb-nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: php-login-service
            port:
              number: 80
              
      - pathType: Prefix
        path: /login_ok.php
        backend:
          service:
            name: php-login-service
            port:
              number: 80

      - pathType: Prefix
        path: /regist
        backend:
          service:
            name: php-regist-service
            port:
              number: 80

      - pathType: Prefix
        path: /regist_ok.php
        backend:
          service:
            name: php-regist-service
            port:
              number: 80

      - pathType: Prefix
        path: /dbconnect
        backend:
          service:
            name: php-service
            port:
              number: 80